# nupy kütüphanesi

In [1]:
import numpy as np
vize = [10,20,30,40]
final = [2,60,32,50]
vize_np = np.array(vize)
final_np = np.array (final)
ortalama = (vize_np + final_np)/2
print(ortalama)

[ 6. 40. 31. 45.]


In [2]:
my_array = np.array([[1,2,3], [4,5,6]])
print(my_array)

[[1 2 3]
 [4 5 6]]


In [3]:
import numpy as np
arr = np.array([1,2,3,4,5])
max_value = np.amax(arr)
print(max_value) # output: 5

5


In [8]:
import numpy as np
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
max_values = np.amax(arr, axis=1)
print(max_values)

[3 6 9]


In [9]:
import numpy as np
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
max_values = np.amax(arr, axis=0)
print(max_values)

[7 8 9]


In [10]:
import numpy as np
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
max_values = np.amax(arr, axis=1, keepdims=True)
print(max_values)

[[3]
 [6]
 [9]]


In [11]:
import numpy as np
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
max_values = np.amax(arr, axis=0, keepdims=True)
print(max_values)

[[7 8 9]]


In [12]:
import numpy as np
arr = np.array([1,2,3,4,5])
max_value =np.amax(arr, initial=0)
print(max_value)

5


In [13]:
import numpy as np
arr = np.array([1,2,3,4,5])
max_value =np.amax(arr, initial=6)
print(max_value)

6


In [15]:
import pandas as pd
my_list = [1,2,3,4,5]
my_series = pd.Series(my_list)
print(my_series)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [24]:
import pandas as pd
my_dict={'name': ['Alice','Bob','Charlie'],'age':[25, 30, 35]}
my_dataframe=pd.DataFrame(my_dict)
print(my_dateframe)

NameError: name 'my_dateframe' is not defined

In [ ]:
#csv dosyasından bir veri okuma
import pandas as pd
my_dataframe=pd.read_csv('data.cvs')
print(my_dataframe)
#excel dosyasından bir veri okuma
my_dataframe = pd.read_excel('data.xlsx')
print(my_dateframe)
#veri çerçevesinden bir CVS dosyası yazma
my_dataframe.to_csv('data.csv',index=False)

In [26]:
import seaborn as sns
iris = sns.load_dataset("iris")
print(iris.head())

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa


In [28]:
import seaborn as sns
iris = sns.load_dataset('C:\Users\BT-101\Downloads\belge1665140792393.xls')
print(iris.head())

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (3859032402.py, line 2)

In [29]:
import pandas as pd
df = pd.read_csv('C:\Users\BT-101\Downloads\belge1665140792393.xls')
print(df.head())

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (1931817851.py, line 2)